[Service]
  Port = 49999
  Timeout = 5000
  ConnectRetries = 10
  Labels = [ 'Template' ]
  StartupMsg = 'Template device started'
  CheckInterval = '10s'

[Clients]
  [Clients.Data]
    Host = 'localhost'
    Port = 48080

  [Clients.Metadata]
    Host = 'localhost'
    Port = 48081

  [Clients.Logging]
    Host = 'localhost'
    Port = 48061

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = ''
  SendReadingsOnChanged = true

[Logging]
  EnableRemote = false
  File = '-'
  LogLevel = 'DEBUG'

[Driver]
  TestParam1 = 'Hello'
  TestParam2 = 'World'

[[DeviceList]]
  Name = 'Device1'
  Profile = 'TemplateSensor'
  Description = 'An Example Template Device'
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = 'someSensorEndpoint'
  [[DeviceList.AutoEvents]]
    Resource = 'SensorOne'
    OnChange = false
    Frequency = '10s'
